### ISSUE TITLE
Incorrect DEQARINST ID on public ui

### ISSUE THREAD

**Issue by kogelnikp** [EQAR/deqar_public_ui#8]
Hi everyone,

I think DEQARINST Ids are displayed in a wrong format on the public website.

In the admin ui the Id is always displayed with four digits padded with leading zeros.
On the public website the leading zeros are missing.

The id on the public website is not working for the submission API. So I assume the id in the admin area is the correct one.

![grafik](https://user-images.githubusercontent.com/8058487/117458786-f521b600-af4a-11eb-8bf9-4bf8d1b7a986.png)
![grafik](https://user-images.githubusercontent.com/8058487/117458803-f8b53d00-af4a-11eb-8454-5ebe42ab036d.png)

**Comment by ctueck** [comment]
fixed by a9f1ee41f9afe768448d10ca5240d977a45554bd
